insert into public.events (
  title,
  slug,
  description,
  city,
  country,
  region,
  start_date,
  end_date,
  organiser,
  association,
  website,
  category,
  event_scope,
  featured,
  approved
)
values
  (
    'Professional Investigators Conference 2026',
    'professional-investigators-conference-2026',
    'Association of British Investigators annual conference for private investigators and related industry professionals.',
    'Newmarket',
    'United Kingdom',
    'Europe',
    '2026-04-17',
    '2026-04-18',
    'Association of British Investigators (ABI)',
    'Association of British Investigators',
    'https://www.theabi.org.uk/events/professional-investigators-conference-2026',
    'Conference',
    'main',
    true,
    true
  ),
  (
    '66th BUDEG General Meeting 2026',
    '66th-budeg-general-meeting-2026',
    'BUDEG general meeting and training programme for investigators and security professionals in Germany.',
    'Bremen',
    'Germany',
    'Europe',
    '2026-04-17',
    '2026-04-19',
    'BUDEG',
    'BUDEG',
    'https://budeg.de/aktuelles/',
    'General Meeting / Training',
    'main',
    true,
    true
  ),
  (
    'Hit the Hill 2026',
    'hit-the-hill-2026',
    'NCISS annual advocacy event bringing investigators and security professionals to meet lawmakers.',
    'National Harbor, MD',
    'United States',
    'North America',
    '2026-03-23',
    '2026-03-24',
    'NCISS',
    'National Council of Investigation and Security Services',
    'https://nciss.org/content.aspx?page_id=4091&club_id=58484&item_id=2859159',
    'Advocacy / Annual Event',
    'main',
    true,
    true
  ),
  (
    '2026 Intellenet Conference',
    '2026-intellenet-conference',
    'Intellenet annual conference covering investigations, intelligence practice, and professional networking.',
    'Philadelphia, PA',
    'United States',
    'North America',
    '2026-04-12',
    '2026-04-16',
    'Intellenet',
    'Intellenet',
    'https://www.intellenet.org/event-6354933',
    'Conference',
    'main',
    true,
    true
  ),
  (
    'FEWA National Expert Witness Conference 2026',
    'fewa-national-expert-witness-conference-2026',
    'FEWA conference focused on expert witness practice, testimony standards, and professional development.',
    'Online',
    'United States',
    'North America',
    '2026-05-14',
    '2026-05-14',
    'FEWA',
    'Forensic Expert Witness Association',
    'https://forensic.org/events/EventDetails.aspx?id=2041072&group=',
    'Conference',
    'main',
    false,
    true
  ),
  (
    '69th Annual Convention Federpol',
    '69th-annual-convention-federpol',
    'FEDERPOL annual convention for licensed investigators, association leadership, and international delegates.',
    'Sorrento',
    'Italy',
    'Europe',
    '2026-05-22',
    '2026-05-23',
    'FEDERPOL',
    'FEDERPOL',
    'https://www.federpol.it/evento/69th-annual-convention-federpol-xxii-ikd-general-assembly/',
    'Annual Convention',
    'main',
    true,
    true
  ),
  (
    'IKD General Assembly 2026',
    'ikd-general-assembly-2026',
    'International assembly session held alongside the Federpol convention in Sorrento.',
    'Sorrento',
    'Italy',
    'Europe',
    '2026-05-23',
    '2026-05-23',
    'IKD / FEDERPOL',
    'IKD',
    'https://www.federpol.it/evento/69th-annual-convention-federpol-xxii-ikd-general-assembly/',
    'General Assembly',
    'main',
    false,
    true
  ),
  (
    'NCAPI Annual Conference',
    'ncapi-annual-conference',
    'Annual NCAPI conference for North Carolina investigators focused on professional updates and networking.',
    'Carolina Beach, NC',
    'United States',
    'North America',
    '2026-04-21',
    '2026-04-22',
    'NCAPI',
    'North Carolina Association of Private Investigators',
    'https://www.ncapi.com/index.php?option=com_jevents&task=icalrepeat.detail&evid=88&Itemid=1&year=2026&month=04&day=21&title=ncapi-annual-conference&uid=38b6fe75a62fe97b587e68d0d812efb4',
    'Annual Conference',
    'main',
    false,
    true
  ),
  (
    '2026 FALI Conference',
    '2026-fali-conference',
    'Florida Association of Licensed Investigators annual conference for state and regional investigator networks.',
    'Orlando, FL',
    'United States',
    'North America',
    '2026-04-30',
    '2026-05-02',
    'FALI',
    'Florida Association of Licensed Investigators',
    'https://www.fali.org/events/EventDetails.aspx?id=2030966&group=',
    'Annual Conference',
    'main',
    true,
    true
  ),
  (
    '2026 TALI Conference',
    '2026-tali-conference',
    'Texas Association of Licensed Investigators annual conference focused on technology-driven investigations.',
    'San Antonio, TX',
    'United States',
    'North America',
    '2026-09-24',
    '2026-09-26',
    'TALI',
    'Texas Association of Licensed Investigators',
    'https://www.tali.org/tali-26-technology-driven-investigations/',
    'Annual Conference',
    'main',
    true,
    true
  ),
  (
    '2026 CALI Annual Conference',
    '2026-cali-annual-conference',
    'California Association of Licensed Investigators annual conference for investigators, vendors, and association members.',
    'Cathedral City, CA',
    'United States',
    'North America',
    '2026-10-08',
    '2026-10-10',
    'CALI',
    'California Association of Licensed Investigators',
    'https://www.cali-pi.org/content.aspx?page_id=4002&club_id=49391&item_id=2719259',
    'Annual Conference',
    'main',
    true,
    true
  ),
  (
    'CII Asian Regional Meeting',
    'cii-asian-regional-meeting',
    'Council of International Investigators regional meeting for members and invited delegates in Asia.',
    'New Delhi',
    'India',
    'Asia-Pacific',
    '2026-03-15',
    '2026-03-17',
    'CII',
    'Council of International Investigators',
    'https://www.cii2.org/index.php?option=com_jevents&task=icalrepeat.detail&evid=145&Itemid=1&year=2026&month=03&day=15&title=asian-regional-meeting-new-delhi-&uid=a3622f58976b0cd689821995610d0971',
    'Regional Meeting',
    'main',
    false,
    true
  ),
  (
    'CII Western US Regional Meeting',
    'cii-western-us-regional-meeting',
    'Council of International Investigators western United States regional meeting for members and partners.',
    'Texas',
    'United States',
    'North America',
    '2026-03-27',
    '2026-03-28',
    'CII',
    'Council of International Investigators',
    'https://www.cii2.org/index.php?option=com_jevents&task=icalrepeat.detail&evid=142&Itemid=1&year=2026&month=03&day=27&title=western-us-regional-meeting-texas-&uid=f516010882320ac2ea8c9d18d160eacf',
    'Regional Meeting',
    'main',
    false,
    true
  ),
  (
    'CII European Regional Meeting',
    'cii-european-regional-meeting',
    'Council of International Investigators regional meeting for European members and international delegates.',
    'Venice',
    'Italy',
    'Europe',
    '2026-05-14',
    '2026-05-16',
    'CII',
    'Council of International Investigators',
    'https://www.cii2.org/index.php?option=com_jevents&task=icalrepeat.detail&evid=138&Itemid=1&year=2026&month=05&day=14&title=european-regional-meeting-venice&uid=3f214c465b5119f9c5bb8623c68f85b0',
    'Regional Meeting',
    'main',
    false,
    true
  ),
  (
    'CII AGM 2026',
    'cii-agm-2026',
    'Council of International Investigators annual general meeting and member programme in Prague.',
    'Prague',
    'Czech Republic',
    'Europe',
    '2026-09-01',
    '2026-09-06',
    'CII',
    'Council of International Investigators',
    'https://www.cii2.org/index.php?option=com_jevents&task=icalrepeat.detail&evid=135&Itemid=1&year=2026&month=09&day=01&title=2026-agm-prague&uid=210c8f032b53b58bc0458f551dce7ae1',
    'AGM',
    'main',
    true,
    true
  ),
  (
    'WAD Conference 2026',
    'wad-conference-2026',
    'World Association of Detectives conference for global investigators, agencies, and association members.',
    'Cannes',
    'France',
    'Europe',
    '2026-09-01',
    '2026-09-06',
    'WAD',
    'World Association of Detectives',
    'https://www.i-k-d.com/index.php?page=events',
    'Conference',
    'main',
    true,
    true
  ),
  (
    'WAD Conference 2027',
    'wad-conference-2027',
    'World Association of Detectives conference for international investigators, agencies, and association members.',
    'San Jose',
    'Costa Rica',
    'North America',
    '2027-03-03',
    '2027-03-07',
    'WAD',
    'World Association of Detectives',
    'https://www.i-k-d.com/index.php?page=events',
    'Conference',
    'main',
    false,
    true
  ),
  (
    'Northern Branch Meeting',
    'northern-branch-meeting',
    'Association of British Investigators northern branch meeting for local members.',
    'Manchester',
    'United Kingdom',
    'Europe',
    '2026-03-13',
    '2026-03-13',
    'ABI',
    'Association of British Investigators',
    'https://www.theabi.org.uk/',
    'Branch Meeting',
    'secondary',
    false,
    true
  ),
  (
    'Southern Branch Meeting',
    'southern-branch-meeting',
    'Association of British Investigators southern branch meeting for members in the region.',
    'London',
    'United Kingdom',
    'Europe',
    '2026-03-25',
    '2026-03-25',
    'ABI',
    'Association of British Investigators',
    'https://www.theabi.org.uk/',
    'Branch Meeting',
    'secondary',
    false,
    true
  ),
  (
    'CALI Webinar: Artificial Intelligence Use Cases for Private Investigators',
    'cali-webinar-artificial-intelligence-use-cases-for-private-investigators',
    'CALI webinar covering practical artificial intelligence use cases for licensed private investigators.',
    'Online',
    'United States',
    'North America',
    '2026-03-18',
    '2026-03-18',
    'CALI',
    'California Association of Licensed Investigators',
    'https://www.cali-pi.org/',
    'Webinar',
    'secondary',
    false,
    true
  ),
  (
    'NLITE (Newly Licensed Investigator Training and Education)',
    'nlite-newly-licensed-investigator-training-and-education',
    'Training event for newly licensed investigators in California.',
    'Sacramento, CA',
    'United States',
    'North America',
    '2026-03-21',
    '2026-03-21',
    'CALI',
    'California Association of Licensed Investigators',
    'https://www.cali-pi.org/',
    'Training',
    'secondary',
    false,
    true
  ),
  (
    'CALI Legislative Day',
    'cali-legislative-day',
    'California Association of Licensed Investigators legislative advocacy day in Sacramento.',
    'Sacramento, CA',
    'United States',
    'North America',
    '2026-03-23',
    '2026-03-23',
    'CALI',
    'California Association of Licensed Investigators',
    'https://www.cali-pi.org/',
    'Legislative',
    'secondary',
    false,
    true
  ),
  (
    'FALI-CDIN Monthly Lunchtime Chat March 2026',
    'fali-cdin-monthly-lunchtime-chat-march-2026',
    'Monthly online member chat hosted by FALI-CDIN.',
    'Online',
    'United States',
    'North America',
    '2026-03-11',
    '2026-03-11',
    'FALI',
    'Florida Association of Licensed Investigators',
    'https://www.fali.org/',
    'Members Webinar',
    'secondary',
    false,
    true
  ),
  (
    'FALI Panhandle Quarterly Meeting',
    'fali-panhandle-quarterly-meeting',
    'Florida regional quarterly meeting for investigators in the Panhandle.',
    'Gulf Breeze, FL',
    'United States',
    'North America',
    '2026-03-18',
    '2026-03-18',
    'FALI',
    'Florida Association of Licensed Investigators',
    'https://www.fali.org/',
    'Regional Meeting',
    'secondary',
    false,
    true
  ),
  (
    'FALI-CDIN Monthly Lunchtime Chat April 2026',
    'fali-cdin-monthly-lunchtime-chat-april-2026',
    'Monthly online member chat hosted by FALI-CDIN.',
    'Online',
    'United States',
    'North America',
    '2026-04-08',
    '2026-04-08',
    'FALI',
    'Florida Association of Licensed Investigators',
    'https://www.fali.org/',
    'Members Webinar',
    'secondary',
    false,
    true
  ),
  (
    'FALI-CDIN Monthly Lunchtime Chat May 2026',
    'fali-cdin-monthly-lunchtime-chat-may-2026',
    'Monthly online member chat hosted by FALI-CDIN.',
    'Online',
    'United States',
    'North America',
    '2026-05-13',
    '2026-05-13',
    'FALI',
    'Florida Association of Licensed Investigators',
    'https://www.fali.org/',
    'Members Webinar',
    'secondary',
    false,
    true
  )
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  city = excluded.city,
  country = excluded.country,
  region = excluded.region,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  organiser = excluded.organiser,
  association = excluded.association,
  website = excluded.website,
  category = excluded.category,
  event_scope = excluded.event_scope,
  featured = excluded.featured,
  approved = excluded.approved;
